receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  debug:
    verbosity: normal
  awsxray:
    region: us-west-2
  awsemf:
    region: us-west-2

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - debug
        - awsxray
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - debug
        - awsemf
